"""change_user_id_from_uuid_to_int

Revision ID: 8174c1fe5a08
Revises: 0f5e27cc08e3
Create Date: 2025-11-17 19:56:29.024272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8174c1fe5a08'
down_revision: Union[str, Sequence[str], None] = '0f5e27cc08e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Сначала удаляем внешние ключи
    op.drop_constraint('addresses_user_id_fkey', 'addresses', type_='foreignkey')
    op.drop_constraint('orders_user_id_fkey', 'orders', type_='foreignkey')
    
    # Создаем последовательность для autoincrement
    op.execute('CREATE SEQUENCE IF NOT EXISTS users_id_seq')
    
    # Изменяем тип колонки users.id (основной ключ)
    # PostgreSQL требует USING для преобразования UUID в integer
    # Для пустой таблицы используем простое преобразование
    op.execute('ALTER TABLE users ALTER COLUMN id TYPE INTEGER USING 1')
    op.execute('ALTER TABLE users ALTER COLUMN id SET DEFAULT nextval(\'users_id_seq\')')
    op.execute('ALTER SEQUENCE users_id_seq OWNED BY users.id')
    
    # Изменяем типы внешних ключей
    op.execute('ALTER TABLE addresses ALTER COLUMN user_id TYPE INTEGER USING 1')
    op.execute('ALTER TABLE orders ALTER COLUMN user_id TYPE INTEGER USING 1')
    
    # Восстанавливаем внешние ключи
    op.create_foreign_key('addresses_user_id_fkey', 'addresses', 'users', ['user_id'], ['id'])
    op.create_foreign_key('orders_user_id_fkey', 'orders', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Удаляем внешние ключи
    op.drop_constraint('orders_user_id_fkey', 'orders', type_='foreignkey')
    op.drop_constraint('addresses_user_id_fkey', 'addresses', type_='foreignkey')
    
    # Изменяем типы обратно на UUID
    op.alter_column('orders', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('addresses', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False,
               autoincrement=True)
    
    # Восстанавливаем внешние ключи
    op.create_foreign_key('addresses_user_id_fkey', 'addresses', 'users', ['user_id'], ['id'])
    op.create_foreign_key('orders_user_id_fkey', 'orders', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
