"""change_uuid_to_int_for_all_models

Revision ID: 9e6b96ed2170
Revises: eeb0a18a7fdf
Create Date: 2025-11-24 15:12:14.725753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e6b96ed2170'
down_revision: Union[str, Sequence[str], None] = 'eeb0a18a7fdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Удаляем все внешние ключи, которые ссылаются на изменяемые колонки
    op.drop_constraint('order_items_order_id_fkey', 'order_items', type_='foreignkey')
    op.drop_constraint('order_items_product_id_fkey', 'order_items', type_='foreignkey')
    op.drop_constraint('orders_delivery_address_id_fkey', 'orders', type_='foreignkey')
    
    # Создаем последовательности для autoincrement
    op.execute('CREATE SEQUENCE IF NOT EXISTS addresses_id_seq')
    op.execute('CREATE SEQUENCE IF NOT EXISTS products_id_seq')
    op.execute('CREATE SEQUENCE IF NOT EXISTS orders_id_seq')
    op.execute('CREATE SEQUENCE IF NOT EXISTS order_items_id_seq')
    
    # Изменяем addresses.id
    op.execute('ALTER TABLE addresses ALTER COLUMN id TYPE INTEGER USING 1')
    op.execute('ALTER TABLE addresses ALTER COLUMN id SET DEFAULT nextval(\'addresses_id_seq\')')
    op.execute('ALTER SEQUENCE addresses_id_seq OWNED BY addresses.id')
    
    # Изменяем products.id
    op.execute('ALTER TABLE products ALTER COLUMN id TYPE INTEGER USING 1')
    op.execute('ALTER TABLE products ALTER COLUMN id SET DEFAULT nextval(\'products_id_seq\')')
    op.execute('ALTER SEQUENCE products_id_seq OWNED BY products.id')
    
    # Изменяем orders.id
    op.execute('ALTER TABLE orders ALTER COLUMN id TYPE INTEGER USING 1')
    op.execute('ALTER TABLE orders ALTER COLUMN id SET DEFAULT nextval(\'orders_id_seq\')')
    op.execute('ALTER SEQUENCE orders_id_seq OWNED BY orders.id')
    
    # Изменяем orders.delivery_address_id
    op.execute('ALTER TABLE orders ALTER COLUMN delivery_address_id TYPE INTEGER USING 1')
    
    # Изменяем order_items.id
    op.execute('ALTER TABLE order_items ALTER COLUMN id TYPE INTEGER USING 1')
    op.execute('ALTER TABLE order_items ALTER COLUMN id SET DEFAULT nextval(\'order_items_id_seq\')')
    op.execute('ALTER SEQUENCE order_items_id_seq OWNED BY order_items.id')
    
    # Изменяем order_items.order_id и product_id
    op.execute('ALTER TABLE order_items ALTER COLUMN order_id TYPE INTEGER USING 1')
    op.execute('ALTER TABLE order_items ALTER COLUMN product_id TYPE INTEGER USING 1')
    
    # Восстанавливаем внешние ключи
    op.create_foreign_key('order_items_order_id_fkey', 'order_items', 'orders', ['order_id'], ['id'])
    op.create_foreign_key('order_items_product_id_fkey', 'order_items', 'products', ['product_id'], ['id'])
    op.create_foreign_key('orders_delivery_address_id_fkey', 'orders', 'addresses', ['delivery_address_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Удаляем внешние ключи
    op.drop_constraint('orders_delivery_address_id_fkey', 'orders', type_='foreignkey')
    op.drop_constraint('order_items_product_id_fkey', 'order_items', type_='foreignkey')
    op.drop_constraint('order_items_order_id_fkey', 'order_items', type_='foreignkey')
    
    # Изменяем типы обратно на UUID
    op.execute('ALTER TABLE order_items ALTER COLUMN product_id TYPE UUID USING gen_random_uuid()')
    op.execute('ALTER TABLE order_items ALTER COLUMN order_id TYPE UUID USING gen_random_uuid()')
    op.execute('ALTER TABLE order_items ALTER COLUMN id TYPE UUID USING gen_random_uuid()')
    op.execute('ALTER TABLE order_items ALTER COLUMN id DROP DEFAULT')
    
    op.execute('ALTER TABLE orders ALTER COLUMN delivery_address_id TYPE UUID USING gen_random_uuid()')
    op.execute('ALTER TABLE orders ALTER COLUMN id TYPE UUID USING gen_random_uuid()')
    op.execute('ALTER TABLE orders ALTER COLUMN id DROP DEFAULT')
    
    op.execute('ALTER TABLE products ALTER COLUMN id TYPE UUID USING gen_random_uuid()')
    op.execute('ALTER TABLE products ALTER COLUMN id DROP DEFAULT')
    
    op.execute('ALTER TABLE addresses ALTER COLUMN id TYPE UUID USING gen_random_uuid()')
    op.execute('ALTER TABLE addresses ALTER COLUMN id DROP DEFAULT')
    
    # Удаляем последовательности
    op.execute('DROP SEQUENCE IF EXISTS order_items_id_seq')
    op.execute('DROP SEQUENCE IF EXISTS orders_id_seq')
    op.execute('DROP SEQUENCE IF EXISTS products_id_seq')
    op.execute('DROP SEQUENCE IF EXISTS addresses_id_seq')
    
    # Восстанавливаем внешние ключи
    op.create_foreign_key('order_items_order_id_fkey', 'order_items', 'orders', ['order_id'], ['id'])
    op.create_foreign_key('order_items_product_id_fkey', 'order_items', 'products', ['product_id'], ['id'])
    op.create_foreign_key('orders_delivery_address_id_fkey', 'orders', 'addresses', ['delivery_address_id'], ['id'])
    # ### end Alembic commands ###
