"""add reports table

Revision ID: bf507bdc6f82
Revises: 9e6b96ed2170
Create Date: 2025-12-16 16:24:03.961616

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bf507bdc6f82'
down_revision: Union[str, Sequence[str], None] = '9e6b96ed2170'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_at', sa.Date(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('count_product', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_report_at_order_id', 'reports', ['report_at', 'order_id'], unique=False)
    op.create_index(op.f('ix_reports_order_id'), 'reports', ['order_id'], unique=False)
    op.create_index(op.f('ix_reports_report_at'), 'reports', ['report_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_report_at'), table_name='reports')
    op.drop_index(op.f('ix_reports_order_id'), table_name='reports')
    op.drop_index('idx_report_at_order_id', table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
